on: [push]
jobs:
  deutschland_generation:
    name: "Deutschland Generation"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11.1' ]
    steps:
      - uses: actions/checkout@v2

      # Create default .spectral.yaml file used for linting if its not existing already
      - name: "Create spectral file if it not exists"
        continue-on-error: true
        run: |
           set -C; echo "extends: spectral:oas" > .spectral.yaml
      # Runs a single command using the runners shell
      - name: "Lint file"
        uses: stoplightio/spectral-action@latest
        with:
            file_glob: "openapi.yaml"

      - name: "Generate deutschland code"
        uses: wirthual/deutschland-generator-action@latest
        with:
          openapi-file: ${{ github.workspace }}/openapi.yaml
          commit-to-git: true
          upload-to-pypi: true
          upload-to-testpypi: false
          pypi-token: ${{ secrets.PYPI_PRODUCTION }}
          testpypi-token: ${{ secrets.PYPI_TEST }}
          python-version: ${{ matrix.python-version }}
