on: [push, pull_request]
jobs:
    openapi_check:
      name: "OpenAPI check"
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: swagger-cli
          uses: vaibhav-jain/spectral-action/@v2.6
          with:
            file_path: openapi.yaml